wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1710364175.0
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 14
      - 15
      - 23
      4: 3.8.18
      5: 0.16.4
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
